server:
  port: 10010

spring:
  application:
    name: module-demo-ribbon

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:10001/eureka/,http://eureka-server2:10002/eureka/
