server:
  port: 10010
spring:
  application:
    name: module-demo-ribbon
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试
#注册中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:10001/eureka/,http://eureka-server2:10002/eureka/
    #表示eureka client间隔多久去拉取服务注册信息，默认为30秒，
    #对于api-gateway，如果要迅速获取服务注册状态，可以缩小该值，比如5秒
    registry-fetch-interval-seconds: 15
# 指定设置module-user-service 表示作用到哪个微服务
module-user-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置规则 随机
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule #配置规则 轮询
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RetryRule #配置规则 重试
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule #配置规则 响应时间权重
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    #以下的配置需要配合fegin使用
#    ConnectTimeout: 500 #请求连接超时时间
#    ReadTimeout: 500 #请求处理的超时时间
#    OkToRetryOnAllOperations: true #对所有请求都进行重试
#    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
#    MaxAutoRetries: 3 #对当前实例的重试次数