server:
  port: 10121

spring:
  application:
    name: demo-feign-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:10101/eureka/,http://eureka-server2:10102/eureka/

feign:
  hystrix:
    enabled: true